# Generated by Django 5.1.6 on 2025-02-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('full_text', models.TextField()),
                ('summary', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('pubdate', models.DateTimeField()),
                ('slug', models.CharField(max_length=225, unique=True)),
            ],
        ),
    ]
